{"endpoint": "https://general-rag-store.search.windows.net", "index_name": "documents-index", "timestamp": "2025-08-27T12:18:09.906451Z", "level": "info", "event": "AISearchManager initialized"}
{"timestamp": "2025-08-27T12:18:09.908155Z", "level": "error", "event": "Error in [/Users/anujpandey/llm_projects/end_to_end_projects/adek_ai_v2/src/data_ingestion/ingestion.py] at line [439]\nMessage: Pipeline execution failed: Error in [/Users/anujpandey/llm_projects/end_to_end_projects/adek_ai_v2/src/data_ingestion/ingestion.py] at line [248]\nMessage: Failed to initialize ChatIngestor: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable\nTraceback:\nTraceback (most recent call last):\n  File \"/Users/anujpandey/llm_projects/end_to_end_projects/adek_ai_v2/src/data_ingestion/ingestion.py\", line 248, in __init__\n    self.embeddings = OpenAIEmbeddings(api_key=openai_api_key)\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/anujpandey/llm_projects/end_to_end_projects/adek_ai_v2/.venv/lib/python3.12/site-packages/pydantic/main.py\", line 253, in __init__\n    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/anujpandey/llm_projects/end_to_end_projects/adek_ai_v2/.venv/lib/python3.12/site-packages/langchain_openai/embeddings/base.py\", line 328, in validate_environment\n    self.client = openai.OpenAI(**client_params, **sync_specific).embeddings  # type: ignore[arg-type]\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/anujpandey/llm_projects/end_to_end_projects/adek_ai_v2/.venv/lib/python3.12/site-packages/openai/_client.py\", line 132, in __init__\n    raise OpenAIError(\nopenai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable\n\nTraceback:\nTraceback (most recent call last):\n  File \"/Users/anujpandey/llm_projects/end_to_end_projects/adek_ai_v2/src/data_ingestion/ingestion.py\", line 248, in __init__\n    self.embeddings = OpenAIEmbeddings(api_key=openai_api_key)\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/anujpandey/llm_projects/end_to_end_projects/adek_ai_v2/.venv/lib/python3.12/site-packages/pydantic/main.py\", line 253, in __init__\n    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/anujpandey/llm_projects/end_to_end_projects/adek_ai_v2/.venv/lib/python3.12/site-packages/langchain_openai/embeddings/base.py\", line 328, in validate_environment\n    self.client = openai.OpenAI(**client_params, **sync_specific).embeddings  # type: ignore[arg-type]\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/anujpandey/llm_projects/end_to_end_projects/adek_ai_v2/.venv/lib/python3.12/site-packages/openai/_client.py\", line 132, in __init__\n    raise OpenAIError(\nopenai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/anujpandey/llm_projects/end_to_end_projects/adek_ai_v2/src/data_ingestion/ingestion.py\", line 439, in <module>\n    chat_ingestor = ChatIngestor(\n                    ^^^^^^^^^^^^^\n  File \"/Users/anujpandey/llm_projects/end_to_end_projects/adek_ai_v2/src/data_ingestion/ingestion.py\", line 266, in __init__\n    raise CommonException(f\"Failed to initialize ChatIngestor: {e}\", sys)\nexception.custom_exception.CommonException: Error in [/Users/anujpandey/llm_projects/end_to_end_projects/adek_ai_v2/src/data_ingestion/ingestion.py] at line [248]\nMessage: Failed to initialize ChatIngestor: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable\nTraceback:\nTraceback (most recent call last):\n  File \"/Users/anujpandey/llm_projects/end_to_end_projects/adek_ai_v2/src/data_ingestion/ingestion.py\", line 248, in __init__\n    self.embeddings = OpenAIEmbeddings(api_key=openai_api_key)\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/anujpandey/llm_projects/end_to_end_projects/adek_ai_v2/.venv/lib/python3.12/site-packages/pydantic/main.py\", line 253, in __init__\n    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/anujpandey/llm_projects/end_to_end_projects/adek_ai_v2/.venv/lib/python3.12/site-packages/langchain_openai/embeddings/base.py\", line 328, in validate_environment\n    self.client = openai.OpenAI(**client_params, **sync_specific).embeddings  # type: ignore[arg-type]\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/anujpandey/llm_projects/end_to_end_projects/adek_ai_v2/.venv/lib/python3.12/site-packages/openai/_client.py\", line 132, in __init__\n    raise OpenAIError(\nopenai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable\n\n"}
